// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtcpkjtvnwnszjfakzza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0Y3BranR2bnduc3pqZmFrenphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxODYwMDUsImV4cCI6MjA2Mjc2MjAwNX0.jGEyMvua6tpc4MME4qQG7UJDXX3JdYrV2pZdCRx7W3Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);